services:
    _defaults:
        autowire: true
        public: false
        bind:
            $entityRouterManager: '@lyssal.entity_router'

    Lyssal\BlogBundle\Appellation\BlogAppellation:
        tags:
            - { name: 'lyssal.appellation' }

    Lyssal\BlogBundle\Appellation\CategoryAppellation:
        tags:
            - { name: 'lyssal.appellation' }

    Lyssal\BlogBundle\Appellation\PostAppellation:
        tags:
            - { name: 'lyssal.appellation' }
