easy_admin:
    entities:
        Category:
            class: '%lyssal.blog.entity.category.class%'
            form:
                fields:
                    - 'blog'
                    - { type: 'section', label: 'seo.informations' }
                    - { property: 'page', label: false, type: 'Lyssal\SeoBundle\Form\Type\PageType' }
                    - { type: 'divider' }
                    - 'parent'
                    - 'position'
