imports:
    - { resource: 'services/*.yaml' }

parameters:
    lyssal.blog.entity.blog.class: 'Lyssal\BlogBundle\Entity\Blog'
    lyssal.blog.entity.category.class: 'Lyssal\BlogBundle\Entity\Category'
    lyssal.blog.entity.post.class: 'Lyssal\BlogBundle\Entity\Post'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $blogClassname: '%lyssal.blog.entity.blog.class%'
            $categoryClassname: '%lyssal.blog.entity.category.class%'
            $postClassname: '%lyssal.blog.entity.post.class%'
            $appellationManager: '@lyssal.appellation'
            $postManager: '@lyssal.blog.manager.post'

    Lyssal\BlogBundle\:
        resource: '../../{Form}/'

    Lyssal\BlogBundle\Syndication\PostGenerator:
        public: true
